name: full_game_ui
description: Full Game UI Base
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flame: ^1.17.0
  audioplayers: ^5.2.1
  model_viewer_plus: ^1.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  
  # à¦¤à§‹à¦®à¦¾à¦° à¦†à¦ªà¦²à§‹à¦¡ à¦•à¦°à¦¾ à¦¨à¦¤à§à¦¨ à¦…à§à¦¯à¦¾à¦¸à§‡à¦Ÿ ðŸ“¦
  assets:
    - assets/models/survival_character.glb
    
