name: jungle_escape
description: A 3D Jungle Survival RPG.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  model_viewer_plus: ^1.7.0 # à§©à¦¡à¦¿ à¦®à¦¡à§‡à¦² à¦­à¦¿à¦‰à§Ÿà¦¾à¦° à¦ªà§à¦¯à¦¾à¦•à§‡à¦œ ðŸ“¦

flutter:
  uses-material-design: true
  assets:
    - assets/models/archer.glb # à§©à¦¡à¦¿ à¦®à¦¡à§‡à¦² à¦«à¦¾à¦‡à¦² ðŸ¹
    - assets/images/player_avatar.png # à¦ªà§à¦²à§‡à§Ÿà¦¾à¦° à¦…à¦¬à¦¤à¦¾à¦° à¦‡à¦®à§‡à¦œ ðŸ‘¤
    
